import { TEACHER_IMAGES } from '../imageConstants';

export const TTC_TEACHERS = [
  {
    id: 1,
    name: 'Ashish Rawat',
    title: 'Lead Instructor & Founder',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_1,
    experience: '23+ Years',
    specialty: 'Ashtanga Yoga',
    bio: 'Master in traditional Ashtanga Yoga and alignment with deep spiritual knowledge.',
    credentials: ['E-RYT 500', 'Yoga Alliance Certified', 'Traditional Guru Lineage'],
    expertise: ['Asana Practice', 'Pranayama', 'Meditation', 'Philosophy'],
  },
  {
    id: 2,
    name: 'Priya Sharma',
    title: 'Senior Yoga Instructor',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_2,
    experience: '15+ Years',
    specialty: 'Hatha Yoga',
    bio: 'Expert in Hatha Yoga with focus on therapeutic applications and anatomy.',
    credentials: ['RYT 500', 'Anatomy Specialist', 'Therapeutic Yoga Certified'],
    expertise: ['Therapeutic Yoga', 'Anatomy', 'Alignment', 'Modifications'],
  },
  {
    id: 3,
    name: 'Rajesh Kumar',
    title: 'Philosophy & Meditation Teacher',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_3,
    experience: '18+ Years',
    specialty: 'Yoga Philosophy',
    bio: 'Scholar in ancient yoga texts and traditional meditation practices.',
    credentials: ['Sanskrit Scholar', 'Meditation Master', 'Philosophy Expert'],
    expertise: ['Yoga Sutras', 'Bhagavad Gita', 'Meditation', 'Sanskrit'],
  },
  {
    id: 4,
    name: 'Sunita Devi',
    title: 'Pranayama Specialist',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_1,
    experience: '12+ Years',
    specialty: 'Pranayama',
    bio: 'Specialist in breathing techniques and energy practices for healing.',
    credentials: ['Pranayama Master', 'Energy Healer', 'RYT 300'],
    expertise: ['Breathing Techniques', 'Energy Work', 'Stress Relief', 'Healing'],
  },
  {
    id: 5,
    name: 'Vikram Singh',
    title: 'Anatomy & Physiology',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_2,
    experience: '10+ Years',
    specialty: 'Yoga Anatomy',
    bio: 'Doctor specializing in yoga anatomy and injury prevention techniques.',
    credentials: ['MD', 'Yoga Therapist', 'Sports Medicine'],
    expertise: ['Human Anatomy', 'Injury Prevention', 'Biomechanics', 'Safety'],
  },
  {
    id: 6,
    name: 'Maya Patel',
    title: 'Ayurveda & Nutrition',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_3,
    experience: '14+ Years',
    specialty: 'Ayurveda',
    bio: 'Ayurvedic practitioner integrating nutrition with yoga practice.',
    credentials: ['Ayurvedic Doctor', 'Nutritionist', 'Herbalist'],
    expertise: ['Ayurvedic Medicine', 'Nutrition', 'Detox', 'Wellness'],
  },
  {
    id: 7,
    name: 'Amit Joshi',
    title: 'Kirtan & Mantra',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_1,
    experience: '16+ Years',
    specialty: 'Sacred Music',
    bio: 'Master of traditional kirtan and mantra chanting for spiritual practice.',
    credentials: ['Classical Musician', 'Mantra Master', 'Voice Coach'],
    expertise: ['Kirtan', 'Mantra Chanting', 'Sacred Music', 'Voice Training'],
  },
  {
    id: 8,
    name: 'Deepika Verma',
    title: 'Yin & Restorative Yoga',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_2,
    experience: '11+ Years',
    specialty: 'Yin Yoga',
    bio: 'Expert in gentle yoga practices for relaxation and stress relief.',
    credentials: ['Yin Yoga Certified', 'Restorative Specialist', 'RYT 500'],
    expertise: ['Yin Yoga', 'Restorative Yoga', 'Relaxation', 'Stress Relief'],
  },
  {
    id: 9,
    name: 'Ravi Menon',
    title: 'Advanced Asana',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_3,
    experience: '20+ Years',
    specialty: 'Advanced Poses',
    bio: 'Expert in advanced asana practice and progressive yoga techniques.',
    credentials: ['Advanced Practitioner', 'Acrobatic Yoga', 'E-RYT 500'],
    expertise: ['Advanced Asanas', 'Arm Balances', 'Inversions', 'Flow Sequences'],
  },
  {
    id: 10,
    name: 'Kavita Nair',
    title: "Women's Yoga",
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_1,
    experience: '13+ Years',
    specialty: 'Prenatal Yoga',
    bio: "Specialist in yoga for women's health and prenatal care.",
    credentials: ['Prenatal Certified', "Women's Health", 'Birth Doula'],
    expertise: ['Prenatal Yoga', "Women's Health", 'Fertility', 'Hormonal Balance'],
  },
  {
    id: 11,
    name: 'Sanjay Gupta',
    title: 'Business of Yoga',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_2,
    experience: '8+ Years',
    specialty: 'Yoga Business',
    bio: 'Entrepreneur helping yoga teachers build successful practices.',
    credentials: ['Business Coach', 'Marketing Expert', 'E-RYT 200'],
    expertise: ['Business Development', 'Marketing', 'Online Teaching', 'Entrepreneurship'],
  },
  {
    id: 12,
    name: 'Anita Reddy',
    title: 'Kids & Family Yoga',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_3,
    experience: '9+ Years',
    specialty: 'Kids Yoga',
    bio: 'Specialist in making yoga fun and accessible for children and families.',
    credentials: ['Kids Yoga Certified', 'Family Therapist', 'RYT 300'],
    expertise: ["Children's Yoga", 'Family Classes', 'Play Therapy', 'Child Development'],
  },
  {
    id: 13,
    name: 'Mohan Lal',
    title: 'Senior Practitioner',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_1,
    experience: '25+ Years',
    specialty: 'Traditional Yoga',
    bio: 'Elder teacher maintaining traditional yoga wisdom and practices.',
    credentials: ['Traditional Lineage', 'Sanskrit Scholar', 'Spiritual Guide'],
    expertise: ['Traditional Practices', 'Spiritual Guidance', 'Meditation', 'Wisdom Teachings'],
  },
  {
    id: 14,
    name: 'Neha Agarwal',
    title: 'Yoga Therapy',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_2,
    experience: '12+ Years',
    specialty: 'Therapeutic Yoga',
    bio: 'Certified yoga therapist specializing in healing through yoga practice.',
    credentials: ['C-IAYT', 'Physical Therapist', 'Trauma-Informed'],
    expertise: ['Yoga Therapy', 'Rehabilitation', 'Pain Management', 'Mental Health'],
  },
  {
    id: 15,
    name: 'Arjun Kapoor',
    title: 'Power & Vinyasa',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_3,
    experience: '14+ Years',
    specialty: 'Power Yoga',
    bio: 'Dynamic teacher specializing in powerful flow sequences and strength building.',
    credentials: ['Power Yoga Certified', 'Athletic Training', 'E-RYT 300'],
    expertise: ['Power Yoga', 'Vinyasa Flow', 'Strength Training', 'Athletic Performance'],
  },
  {
    id: 16,
    name: 'Lakshmi Iyer',
    title: 'Meditation Master',
    image: TEACHER_IMAGES.FOUNDERS.FOUNDER_1,
    experience: '22+ Years',
    specialty: 'Meditation',
    bio: 'Master meditation teacher with expertise in various contemplative practices.',
    credentials: ['Meditation Master', 'Mindfulness Teacher', 'Retreat Leader'],
    expertise: ['Vipassana', 'Mindfulness', 'Concentration', 'Silent Retreats'],
  },
] as const;
